name: DarrelWebber
favicon: null
layout_spectrum: 0.4752539419569075
typography_spectrum: 0.8909980738535523
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.7022798515390605
  lightness: 0.1823766785673797
  saturation: 0.3792451648041606
  rhythmicContrast: 0.7824104602914304
purpose: []
