analytics: {}
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.702279
  lightness: 0.182376
  rhythmicContrast: 0.488738
  saturation: 0.379245
cta: {}
layout_spectrum: 0.663288
name: DarrelWebber
opengraph: {}
purpose: []
typography_spectrum: 0.8909980738535523
