name: DarrelWebber
favicon: null
layout_spectrum: 0.25323
typography_spectrum: 0.74633
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.702279
  lightness: 0.497747
  saturation: 0.379245
  rhythmicContrast: 0.488738
purpose: []
